### ISSUE TITLE
修改标签栏文字

### ISSUE THREAD

**Issue by xiejiachen** [Oneflow-Inc/oneflow-documentation#147]
Oneflow![image](https://user-images.githubusercontent.com/16185716/89048393-598f6380-d382-11ea-87c1-a17c31c92e3c.png)建议改为Github。

移动端出现重复了

**Comment by xiejiachen** [comment]
标签栏右上角的Oneflow建议改为Github

**Comment by Flowingsun007** [comment]
> 标签栏右上角的Oneflow建议改为Github

已修改
