### ISSUE TITLE
Dead link for "OneFlow-Toolkit"

### ISSUE THREAD

**Issue by GHGmc2** [Oneflow-Inc/oneflow-documentation#151]
page link: https://docs.oneflow.org/contribute/intro.html#_1

> [OneFlow-Toolkit](https://github.com/Oneflow-Inc/oneflow_toolkit)：包含 OneFlow 在训练过程中的日志解析、训练调试、数据转换等工具

**Comment by doombeaker** [comment]
Some code of the OneFlow-Toolkit repo is outdated and should be updated. We will refine that repo and make it public as soon as possible. 
Invalid links will be removed temporarily.
