### ISSUE TITLE
示意图注意事项

### ISSUE THREAD

**Issue by MARD1NO** [Oneflow-Inc/oneflow-documentation#163]
![image](https://user-images.githubusercontent.com/42901638/89181488-7320ed00-d5c6-11ea-950d-d3b25c4217e3.png)
![image](https://user-images.githubusercontent.com/42901638/89181497-77e5a100-d5c6-11ea-8c71-eaa98229c265.png)

**Comment by xiejiachen** [comment]
相同的目的，建议统一风格

![20d1cff66e3a8d6c551f66ef7a62df2](https://user-images.githubusercontent.com/16185716/89181795-fb06f700-d5c6-11ea-82b0-2c229d24c132.png)
![83c6d123ccbe8c389423c098a619b45](https://user-images.githubusercontent.com/16185716/89181806-fe01e780-d5c6-11ea-9506-d73b13f2f1c0.png)

**Comment by doombeaker** [comment]
虚线是应该保留的，看原文可以知道，这代表了网络的层次，体现了网络再物理设备上和逻辑上的网络的层次有对应关系。

用白色底和虚线的方案我也试过，不好看（可能我方式不对），所以当初没采用

**Comment by xiejiachen** [comment]
> 虚线是应该保留的，看原文可以知道，这代表了网络的层次，体现了网络再物理设备上和逻辑上的网络的层次有对应关系。
> 
> 
> 
> 用白色底和虚线的方案我也试过，不好看（可能我方式不对），所以当初没采用

把粉红色的图还有第一个底图都给我，我来搞定

**Comment by xiejiachen** [comment]
@doombeaker 
可以给我标红字的那个图嘛，Data Parallelism那张。给我的PPT里木有这个
