### ISSUE TITLE
possible improvement: 异步迭代训练

### ISSUE THREAD

**Issue by xmyqsh** [Oneflow-Inc/oneflow-documentation#254]
为了充分发挥流式计算的优势，oneflow 不必局限在  forward->backwark->update 这种范式下, conv1不需要 hungry 等待梯度update, 可以直接 produce and consume 下一张图片

当然，这样的话，相同的网络 需要更大的显存和线程并发, 但是如果 oneflow 可以利用其特有的架构和调度优势,  保证多设备扩充线性增长的话, 这个想法还是可以尝试一下的

**Comment by xmyqsh** [comment]
Anyone hear me?
Just like [Figure3](https://cs.stanford.edu/~matei/papers/2019/sosp_pipedream.pdf) in [pipestream](https://github.com/msr-fiddle/pipedream)

**Comment by yuanms2** [comment]
> Anyone hear me?
> Just like [Figure3](https://cs.stanford.edu/~matei/papers/2019/sosp_pipedream.pdf) in [pipestream](https://github.com/msr-fiddle/pipedream)

Thanks, great idea indeed.  OneFlow once implemented and and support such features. However, we found it is seldom used in real world applications and it made the system too complicated. Therefore, we temporally disable it. 

We have the plan to further support it in the future with a simpler design. If you have interest, we can discuss the details with a phone call.

**Comment by xmyqsh** [comment]
Thanks for your phone call.
I have gone through the paper.
Ops.. It is Figure 4 and PipeDream.
By the way, asynchronous parallel has been proved with a low statistical efficiency which cannot reduce training time.

Anyway, PipeDream has designed a best combination of data parallelism and model parallelism. Furthermore, its model parallelism design is awesome!
In my opinion, the methodology behind it applys for any training applications with distributed machines.
It is not too complicate and worth for oneflow to support it.
Hope for the updates!
I will close this issue.
