### ISSUE TITLE
mirrored_strategy.py运行报错

### ISSUE THREAD

**Issue by xiezipeng-ML** [Oneflow-Inc/oneflow-documentation#313]
地址：https://docs.oneflow.org/extended_topics/consistent_mirrored.html
出错位置：https://docs.oneflow.org/code/extended_topics/mirrored_strategy.py
使用oneflow-0.4.0+cu102运行报错如下：

E0623 16:47:01.528753 12611 py_remote_blob.cpp:58] WARNING:
You access a consistent blob shape in mirrored view, there may be problems,
you should add 'x = flow.cast_to_current_logical_view(x)'.
E0623 16:47:01.533601 12611 py_remote_blob.cpp:58] WARNING:
You access a consistent blob shape in mirrored view, there may be problems,
you should add 'x = flow.cast_to_current_logical_view(x)'.
E0623 16:47:01.579418 12611 py_remote_blob.cpp:58] WARNING:
You access a consistent blob shape in mirrored view, there may be problems,
you should add 'x = flow.cast_to_current_logical_view(x)'.
E0623 16:47:01.579546 12611 py_remote_blob.cpp:58] WARNING:
You access a consistent blob shape in mirrored view, there may be problems,
you should add 'x = flow.cast_to_current_logical_view(x)'.
WARNING: return tensor list will concat as axis = 0.
Traceback (most recent call last):
  File "/home/xiezipeng/my_test/my_exp.py", line 52, in <module>
    total_loss = np.array([*loss[0], *loss[1]])
IndexError: list index out of range

可能是数据并行的结果已经自动合并在loss[0]中

**Comment by doombeaker** [comment]
感谢指出，原因是 OneFlow 版本升级造成的接口行为改变。
已经在 https://github.com/Oneflow-Inc/oneflow-documentation/pull/315 修复，谢谢！
