### ISSUE TITLE
nn.Graph文档和API持续完善

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow-documentation#386]
先列下点，持续完善。

## 教程文档
https://docs.oneflow.org/master/basics/08_nn_graph.html
- [x] graph的模型保存和加载，有个独立的说明，加在如何训练之后
- [x] graph文档中，在graph直接添加参数的例子，应该需要去掉，因为保存模型时，没有nn.Module的支持

上面两点已经沟通， @doombeaker 负责推进

## API文档
https://start.oneflow.org/oneflow-api-cn/graph.html

- [ ] 高级特性，如amp的api，需要完善和导出下文档

**Comment by strint** [comment]
model.maxpool-maxpool_2d_9 表示graph下一个名叫model的Module下，名叫maxpool的子Module下，一个op_type_name为maxpool_2d的operation，_9是一个全局唯一的编号（这个改成-9估计是更好的，和前面的op type name区分开）。【在开发一个定位到python代码位置的分支】

Debug graph的文档需要再完善下。

来源讨论：https://github.com/Oneflow-Inc/oneflow/pull/7112#discussion_r775407800

**Comment by doombeaker** [comment]
> 后续把 Graph debug 的解读也放在文档网站上吧 @strint @doombeaker

OK，备忘，我去薅个人。

**Comment by doombeaker** [comment]
这个由 @lixiang007666 负责更新。我 review。 我 合李响先看上文 7112 issue。具体不懂的需要补充的，再找啸宇请教讨论。
李响最近事情也比较多，快则这周内完成，慢则下周内完成。

如果其他人进度上的要求，可以另外提。

**Comment by doombeaker** [comment]
> model.maxpool-maxpool_2d_9 表示graph下一个名叫model的Module下，名叫maxpool的子Module下，一个op_type_name为maxpool_2d的operation，_9是一个全局唯一的编号（这个改成-9估计是更好的，和前面的op type name区分开）。【在开发一个定位到python代码位置的分支】
> 
> Debug graph的文档需要再完善下。
> 
> 来源讨论：[Oneflow-Inc/oneflow#7112 (comment)](https://github.com/Oneflow-Inc/oneflow/pull/7112#discussion_r775407800)

这个的初稿PR @lixiang007666 已经完成：https://github.com/Oneflow-Inc/oneflow-documentation/pull/400#pullrequestreview-841800793

@strint 可以看看吗？

**Comment by strint** [comment]
已经看了。

我觉得可以定下0.6的发布特性check list。

然后针对性的补充下文档。
