### ISSUE TITLE
需要同步更新英文版的 nn.graph 那章的内容。

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/oneflow-documentation#393]
中文版本的 nn.graph 已经更新（见 https://github.com/Oneflow-Inc/oneflow-documentation/pull/391/files ）。

英文版的需要同步更新。

这个交给 @HENGRui6 主要完成吧。

**Comment by HENGRui6** [comment]
已完成
https://github.com/Oneflow-Inc/oneflow-documentation/pull/395
