### ISSUE TITLE
补充与分布式有关的教程文档

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/oneflow-documentation#396]
现在的分布式教程还比较简单，缺少更复杂、实际的大规模的例子。本 issue 记录相关的素材，之后整理为面向用户的教程文档。

- 我们没有 placement 的详细文档。  以及基于 placement 和 sbp 如何配置 混合并行（组间数据并行，组内模型并行）

对应资料：
- https://github.com/Oneflow-Inc/models/blob/18fcb784a6569dbe5ec7dc37f45afb326566b35d/GPT/oneflow_gpt/distribute.py#L130
- https://github.com/Oneflow-Inc/models/blob/18fcb784a6569dbe5ec7dc37f45afb326566b35d/GPT/oneflow_gpt/model.py#L73
- https://github.com/Oneflow-Inc/oneflow/blob/95355aa2970508ee085e981b84934a83f3f43d15/oneflow/api/python/symbol/placement_symbol.cpp#L206

**Comment by doombeaker** [comment]
和后江讨论后，分布式相关重构后的大纲，先存一份备忘：

- 常见的分布式并行策略
- consistent 视角
  - 基本概念
  - SBP Signature 自动推导机制
  - consistent tensor 的用法（多teminal展示）
  - consistent tensor 实战（简单例子，从单机脚本改成 consistent）
  - 注意事项（需要从目前几个项目中收集整理）
  - 2D SBP（需要找郭冉等人确认内容）
- 数据并行实战
- 流水并行实战
- 模型并行实战
- 用 launch 模块启动多进程

**Comment by hjchen2** [comment]
https://github.com/Oneflow-Inc/OneTeam/issues/877

**Comment by doombeaker** [comment]
这个 issue 中的内容阶段性完成了。剩余的refine工作放在 https://github.com/Oneflow-Inc/oneflow-documentation/issues/444 中讨论和执行。
