### ISSUE TITLE
最近的英文文档的同步更新工作

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/oneflow-documentation#407]
之前的中文文档做了更新，主要是这两篇，英文版一直没有同步的。需要找时间同步更新下。这个事情先备忘在这里。之后再组织人做。有空的朋友路过看到了也可以自己认领。

#394 
#401

**Comment by doombeaker** [comment]
任务分配给 @S882li ，分阶段做：

1. 先找出已经合并的，涉及到中文更新，但是英文没更新的 PR，comment 到这个 issue 中
2. 之后，再做翻译的分工，到时在同一个PR中，合作完成

希望下周能够完全完成，如果工作量超出预计，可以调整。

**Comment by S882li** [comment]
翻译任务在这个PR中完成 https://github.com/Oneflow-Inc/oneflow-documentation/pull/420
