### ISSUE TITLE
在  OneFlow Cookies 栏目里添加 ONNX 的文章

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/oneflow-documentation#414]
OneFlow 已经有与  ONNX 相互转换的功能以及教程，教程见：https://docs.oneflow.org/v0.4.0/extended_topics/oneflow_convert_tools.html
和
https://docs.oneflow.org/en/v0.4.0/extended_topics/oneflow_convert_tools.html

不过 0.5.0 发布后，原0.4.0文档的扩展专题不合时宜被隐藏了。

0.7.0 发布过程中，文档网站也会同步更新，届时会引入 OneFlow Cookies 专栏，到时要把 ONNX 这篇教程重新加入进来（中英文版本都需要），并 refine 教程，让它更易懂。

**Comment by doombeaker** [comment]
作为 tutorial 风格的文章，可以参考 pytorch 的这篇文章的风格：https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

内容的话，最好选一个 flowvision 中的预训练模型，这样代码会更简洁。

**Comment by BBuf** [comment]
> 作为 tutorial 风格的文章，可以参考 pytorch 的这篇文章的风格：https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html
> 
> 内容的话，最好选一个 flowvision 中的预训练模型，这样代码会更简洁。

这里需要更新一下了，在eager版本里面已经废弃了onnx->oneflow的功能，所以可以只用介绍oneflow->onnx，我觉得李响可以来refine和重写这篇文章。

**Comment by doombeaker** [comment]
@Alive1024 已经认领这个任务了。左益豪可以了解下上下文。有不动的可以请教 oneflow_onnx 作者 @BBuf 。

不过我觉得其实益豪自己动手做一遍，把 oneflow 模型导出伟 onnx，并且用 onnxruntime 跑起来推理。应该就自己知道怎么重写了。

另外这个公有云项目：https://oneflow.cloud/#/project/public/code?id=366e66fac438ff6b97788b9a56639dbf 里的代码可以参考。以及这个公有云项目的 ipynb，其实是个 OneFlow 公开课教程，也可以参考
