### ISSUE TITLE
Graph的debug的英文文档同步更新

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow-documentation#423]
Graph的debug部分的中文文档已经更新，PR：https://github.com/Oneflow-Inc/oneflow-documentation/pull/416

现在需要同步更新en的英文文档。

<img width="892" alt="image" src="https://user-images.githubusercontent.com/54010254/155078427-88cfa91d-49b2-428b-a965-4d8e722236d0.png">

**Comment by doombeaker** [comment]
@robin978  这个麻烦开个 PR，同步下英文版本。比较急，需要在最近发版前完成。考虑到更新不多（30几行文字），尽量明天中午前完成吧。
