### ISSUE TITLE
需要新增一篇 howto 讲述如何将 PyTorch 预训练模型转为 OneFlow 预训练模型

### ISSUE THREAD

**Issue by doombeaker** [Oneflow-Inc/oneflow-documentation#457]
### 大纲

0. 简要介绍下哪些情况有这种需求
1. 用很简单的 pytorch 代码，搭建个非常简单的  Module，保存为 pth
2. 展示代码，如何加载 `pth` 文件，并转为 OneFlow 模型，且保存
3. 进一步举更实际的例子，以 flowvision 中的模型为例，举例如何将torchvision中的预训练模型，转为 OneFlow 模型，并使用

### 分工

@zhongshsh 负责这篇文章的撰写

**Comment by zhongshsh** [comment]
## flowvision 的 resnet18 没对齐

编写文档时发现 resnet18 模型参数没对齐：
- OneFlow 文档：[flowvision.models.resnet18](https://flowvision.readthedocs.io/en/latest/flowvision.models.html?highlight=resnet18#flowvision.models.resnet18)
- Pytorch 文档：[torchvision.models.resnet18](https://pytorch.org/vision/stable/generated/torchvision.models.resnet18.html?highlight=resnet18#)

```python
import torchvision.models as models_torch
import flowvision.models as models_flow

resnet18_torch = models_torch.resnet18(pretrained=True)
resnet18_flow = models_flow.resnet18()

parameters = resnet18_torch.state_dict()
for key, value in parameters.items():
    val = value.detach().cpu().numpy()
    parameters[key] = val

resnet18_flow.load_state_dict(parameters)
```

错误日志
```shell
Traceback (most recent call last):
  File "vision.py", line 12, in <module>
    resnet18_flow.load_state_dict(parameters)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/nn/module.py", line 470, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for ResNet:
        Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "layer1.0.bn1.num_batches_tracked", "layer1.0.bn2.num_batches_tracked", "layer1.1.bn1.num_batches_tracked", "layer1.1.bn2.num_batches_tracked", "layer2.0.bn1.num_batches_tracked", "layer2.0.bn2.num_batches_tracked", "layer2.0.downsample.1.num_batches_tracked", "layer2.1.bn1.num_batches_tracked", "layer2.1.bn2.num_batches_tracked", "layer3.0.bn1.num_batches_tracked", "layer3.0.bn2.num_batches_tracked", "layer3.0.downsample.1.num_batches_tracked", "layer3.1.bn1.num_batches_tracked", "layer3.1.bn2.num_batches_tracked", "layer4.0.bn1.num_batches_tracked", "layer4.0.bn2.num_batches_tracked", "layer4.0.downsample.1.num_batches_tracked", "layer4.1.bn1.num_batches_tracked", "layer4.1.bn2.num_batches_tracked".
```

**Comment by zhongshsh** [comment]
文档预览：https://zhongshsh.github.io/oneflow-documentation/master/cookies/torch2flow.html

**Comment by MARD1NO** [comment]
这个是新版torch的bn新加的一个参数，之前也有提过一个issue：https://github.com/Oneflow-Inc/oneflow/issues/7440，看看@BBuf 安排谁跟一下

**Comment by zhongshsh** [comment]
## 更新项目文档经验沉淀

一开始拿到 https://github.com/Oneflow-Inc/oneflow-documentation/ 时有点懵，捋了好久才知道如何更新到 gh-pages。感恩 ZuoYihao 同学的部署代码分享，特整理在该 issue 中。

### 更新中文版文档

编写文档并将文档路径加入到 `mkdocs.yml` 后，修改以下代码并运行即可
```shell
cd /workspace/oneflow-documentation/cn/
mkdocs build
cd ./site/
cp -rf * /workspace/oneflow-documentation-web/master
cd /workspace/oneflow-documentation-web
git status
git add .
git commit -m "auto update cn"
git push origin gh-pages
```

说明：`oneflow-documentation-web` 存储的是 gh-pages 分支的代码。

### 更新英文版文档

英文版文档稍有不同，修改以下代码并运行即可
```shell
cd /workspace/oneflow-documentation/en/
mkdocs build
cd ./site/
cp -rf * /workspace/oneflow-documentation-web/en/master
cd /workspace/oneflow-documentation-web
git status
git add .
git commit -m "auto update en"
git push origin gh-pages
```

### 其他

有条件的话可以用 `crontab` 指令将上述代码挂载在后台定时运行。云平台不支持 `crontab` 指令。

**Comment by zhongshsh** [comment]
## 文档比较

- [flowvision documentation](https://flowvision.readthedocs.io/en/latest/index.html)
- [OF documentation](https://oneflow.readthedocs.io/en/master/index.html)

……

**Comment by BBuf** [comment]
> ## flowvision 的 resnet18 没对齐
> 编写文档时发现 resnet18 模型参数没对齐：
> 
> * OneFlow 文档：[flowvision.models.resnet18](https://flowvision.readthedocs.io/en/latest/flowvision.models.html?highlight=resnet18#flowvision.models.resnet18)
> * Pytorch 文档：[torchvision.models.resnet18](https://pytorch.org/vision/stable/generated/torchvision.models.resnet18.html?highlight=resnet18#)
> 
> ```python
> import torchvision.models as models_torch
> import flowvision.models as models_flow
> 
> resnet18_torch = models_torch.resnet18(pretrained=True)
> resnet18_flow = models_flow.resnet18()
> 
> parameters = resnet18_torch.state_dict()
> for key, value in parameters.items():
>     val = value.detach().cpu().numpy()
>     parameters[key] = val
> 
> resnet18_flow.load_state_dict(parameters)
> ```
> 
> 错误日志
> 
> ```shell
> Traceback (most recent call last):
>   File "vision.py", line 12, in <module>
>     resnet18_flow.load_state_dict(parameters)
>   File "/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/nn/module.py", line 470, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)
> RuntimeError: Error(s) in loading state_dict for ResNet:
>         Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "layer1.0.bn1.num_batches_tracked", "layer1.0.bn2.num_batches_tracked", "layer1.1.bn1.num_batches_tracked", "layer1.1.bn2.num_batches_tracked", "layer2.0.bn1.num_batches_tracked", "layer2.0.bn2.num_batches_tracked", "layer2.0.downsample.1.num_batches_tracked", "layer2.1.bn1.num_batches_tracked", "layer2.1.bn2.num_batches_tracked", "layer3.0.bn1.num_batches_tracked", "layer3.0.bn2.num_batches_tracked", "layer3.0.downsample.1.num_batches_tracked", "layer3.1.bn1.num_batches_tracked", "layer3.1.bn2.num_batches_tracked", "layer4.0.bn1.num_batches_tracked", "layer4.0.bn2.num_batches_tracked", "layer4.0.downsample.1.num_batches_tracked", "layer4.1.bn1.num_batches_tracked", "layer4.1.bn2.num_batches_tracked".
> ```

在这个pr解决了：https://github.com/Oneflow-Inc/oneflow/pull/7920
