### ISSUE TITLE
教程中不合理的地方

### ISSUE THREAD

**Issue by rainyq69** [Oneflow-Inc/oneflow-documentation#483]
1. [流水并行训练](https://docs.oneflow.org/master/parallelism/06_pipeline.html) 中缺少一个和 [代码解读](https://docs.oneflow.org/master/parallelism/06_pipeline.html#_2) 同级的二级标题，导致目录不合理
2. [Global Tensor](https://docs.oneflow.org/master/parallelism/03_consistent_tensor.html) 中缺少对 [全局视角与物理视角的映射](https://docs.oneflow.org/master/parallelism/03_consistent_tensor.html#_1) 的描述
3. [Global Tensor](https://docs.oneflow.org/master/parallelism/03_consistent_tensor.html) 中，Terminal1 和 Terminal2 仅环境变量配置不同，其余代码全部一致，故考虑取消两个终端的选项卡。因为只需在此处说明”两个终端的待执行代码完全一致“就足够，省去读者自己挨个切换选项卡检查代码有无差别的”无效时间“。

**Comment by doombeaker** [comment]
分布式专题的教程，等 single-client 的用户界面完工后，会大改。

这部分你关注是很好的。不过离开始 refine 的时间还尚早（应该是发布 v0.9.0 时完成）。你知晓下这个节奏

**Comment by rainyq69** [comment]
> 不过离开始 refine 的时间还尚早（应该是发布 v0.9.0 时完成）。你知晓下这个节奏

晓得了
