### ISSUE TITLE
部分链接失效了

### ISSUE THREAD

**Issue by coderhanjx** [Oneflow-Inc/oneflow-documentation#504]
### 中文部分：

- [oneflow.utils.data.DataLoader](https://oneflow.readthedocs.io/en/master/utils.html#oneflow.utils.data.DataLoader)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/basics/01_quickstart.md?plain=1#L61

- [oneflow.nn.functional](https://oneflow.readthedocs.io/en/master/functional.html)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/basics/02_tensor.md?plain=1#L155

- [oneflow.utils.data.Dataset](https://oneflow.readthedocs.io/en/master/utils.html?highlight=oneflow.utils.data.Dataset#oneflow.utils.data.Dataset)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/basics/03_dataset_dataloader.md?plain=1#L107

- [oneflow.nn.Module](https://oneflow.readthedocs.io/en/master/module.html#oneflow.nn.Module)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/basics/04_build_network.md?plain=1#L3

- [oneflow.nn.functional](https://oneflow.readthedocs.io/en/master/functional.html)和[nn.functional.relu](https://oneflow.readthedocs.io/en/master/functional.html?highlight=relu#oneflow.nn.functional.relu)链接都失效了：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/basics/04_build_network.md?plain=1#L78

- [oneflow.placement](https://start.oneflow.org/oneflow-api-cn/placement.html#oneflow.placement)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/parallelism/04_2d-sbp.md?plain=1#L9

- [DistributedSampler](https://oneflow.readthedocs.io/en/master/utils.html#oneflow.utils.data.distributed.DistributedSampler)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/parallelism/05_ddp.md?plain=1#L184

- [nn.Module.to_global](https://oneflow.readthedocs.io/en/master/module.html?highlight=to_global#oneflow.nn.Module.to_global)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/parallelism/06_pipeline.md?plain=1#L111

- #dlrm打不开：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/cn/docs/cookies/one_embedding.md?plain=1#L206
### 英文部分：

- [oneflow.utils.data.DataLoader](https://oneflow.readthedocs.io/en/master/utils.html#oneflow.utils.data.DataLoader)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/basics/01_quickstart.md?plain=1#L61

- [oneflow.nn.functional](https://oneflow.readthedocs.io/en/master/functional.html)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/basics/02_tensor.md?plain=1#L167

- [oneflow.utils.data.Dataset](https://oneflow.readthedocs.io/en/master/utils.html?highlight=oneflow.utils.data.Dataset#oneflow.utils.data.Dataset)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/basics/03_dataset_dataloader.md?plain=1#L107

- [oneflow.nn.Module](https://oneflow.readthedocs.io/en/master/module.html#oneflow.nn.Module)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/basics/04_build_network.md?plain=1#L3

- [oneflow.nn.functional](https://oneflow.readthedocs.io/en/master/functional.html)和[nn.functional.relu](https://oneflow.readthedocs.io/en/master/functional.html?highlight=relu#oneflow.nn.functional.relu)链接都失效了：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/basics/04_build_network.md?plain=1#L78

- [oneflow.placement](https://start.oneflow.org/oneflow-api-cn/placement.html#oneflow.placement)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/parallelism/04_2d-sbp.md?plain=1#L9

- [DistributedSampler](https://oneflow.readthedocs.io/en/master/utils.html#oneflow.utils.data.distributed.DistributedSampler)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/parallelism/05_ddp.md?plain=1#L183
- [nn.Module.to_global](https://oneflow.readthedocs.io/en/master/module.html?highlight=to_global#oneflow.nn.Module.to_global)链接失效：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/parallelism/06_pipeline.md?plain=1#L113

- #dlrm打不开：
https://github.com/Oneflow-Inc/oneflow-documentation/blob/master/en/docs/cookies/one_embedding.md?plain=1#L198

**Comment by doombeaker** [comment]
> ONNX网站打不开:

这个我这里能打开，可能是你那里的网络问题。
 
![image](https://user-images.githubusercontent.com/3351623/180343812-c363c405-c401-43d8-abad-9533797763ed.png)

**Comment by doombeaker** [comment]
以上只列了中文对应的失效地方，英文的也需要列出（昨天提过的）

**Comment by coderhanjx** [comment]
已经删除onnx网站部分

**Comment by coderhanjx** [comment]
英文部分已更新

**Comment by doombeaker** [comment]
已经在 https://github.com/Oneflow-Inc/oneflow-documentation/pull/507 解决
